name: 'Auto Release Draft'
description: 'Draft a github relese with the changes introduced'
author: 'Marius Mihalcea'
inputs:
  repo-token:
    description: 'the github_token used to authenticate to the current repo'
    required: true
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'


# Define your outputs here.
outputs:
  relese-url:
    description: 'The URL of the GitHub release that was drafted'

runs:
  using: node20
  main: dist/index.js
