name: Build
on: 
    push:
        branches:
            - develop
jobs:
    build:
        name: Build and Test
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [windows-latest,ubuntu-latest]
        steps:
            - name: Get the source code
              uses: actions/checkout@v1
            - name: Restore the dependecies
              run: npm ci
            - name: Build
              run: npm run all